[package]
name = "mc"
version = "0.1.0"
edition = "2021"
description = "Mindustry mlog compiler"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
log = "0.4.17"
pretty_env_logger = "0.4.0"
thiserror = "1.0.31"
